# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='debug_info.proto',
  package='senseAD.pp',
  serialized_pb=_b('\n\x10\x64\x65\x62ug_info.proto\x12\nsenseAD.pp\"\x95\x02\n\x17ParticleFilterDebugInfo\x12\x0f\n\x07p_yeild\x18\x01 \x01(\x01\x12\r\n\x05x_avg\x18\x02 \x01(\x01\x12\r\n\x05y_avg\x18\x03 \x01(\x01\x12\x13\n\x0bv_yield_avg\x18\x04 \x01(\x01\x12\x17\n\x0fv_not_yield_avg\x18\x05 \x01(\x01\x12\x11\n\ttheta_avg\x18\x06 \x01(\x01\x12\x15\n\rintension_avg\x18\x07 \x01(\x01\x12\x18\n\x10tgt_velocity_avg\x18\x08 \x01(\x01\x12\x0f\n\x07x_obser\x18\t \x01(\x01\x12\x0f\n\x07y_obser\x18\n \x01(\x01\x12\x0f\n\x07v_obser\x18\x0b \x01(\x01\x12\x13\n\x0btheta_obser\x18\x0c \x01(\x01\x12\x11\n\ttimestamp\x18\r \x01(\t\"P\n\x13\x45stimationDebugInfo\x12\x39\n\x0c\x66ilter_infos\x18\x01 \x03(\x0b\x32#.senseAD.pp.ParticleFilterDebugInfo\"(\n\nRangeProto\x12\r\n\x05start\x18\x01 \x02(\x01\x12\x0b\n\x03\x65nd\x18\x02 \x02(\x01\"\xd8\x01\n\x0cTimeTagProto\x12/\n\tlongi_tag\x18\x01 \x02(\x0e\x32\x1c.senseAD.pp.ObstacleTagProto\x12\x30\n\x10longi_time_range\x18\x02 \x02(\x0b\x32\x16.senseAD.pp.RangeProto\x12\x31\n\x0blateral_tag\x18\x03 \x02(\x0e\x32\x1c.senseAD.pp.ObstacleTagProto\x12\x32\n\x12lateral_time_range\x18\x04 \x02(\x0b\x32\x16.senseAD.pp.RangeProto\"L\n\x0fTimeTagMapProto\x12\x0e\n\x06id_seq\x18\x01 \x03(\x05\x12)\n\x07tag_seq\x18\x02 \x03(\x0b\x32\x18.senseAD.pp.TimeTagProto*Z\n\x10ObstacleTagProto\x12\t\n\x05YIELD\x10\x01\x12\x0b\n\x07SURPASS\x10\x02\x12\x0e\n\nNUDGE_LEFT\x10\x0b\x12\x0f\n\x0bNUDGE_RIGHT\x10\x0c\x12\r\n\tUNDEFINED\x10\x64')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_OBSTACLETAGPROTO = _descriptor.EnumDescriptor(
  name='ObstacleTagProto',
  full_name='senseAD.pp.ObstacleTagProto',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='YIELD', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SURPASS', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NUDGE_LEFT', index=2, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NUDGE_RIGHT', index=3, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=4, number=100,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=733,
  serialized_end=823,
)
_sym_db.RegisterEnumDescriptor(_OBSTACLETAGPROTO)

ObstacleTagProto = enum_type_wrapper.EnumTypeWrapper(_OBSTACLETAGPROTO)
YIELD = 1
SURPASS = 2
NUDGE_LEFT = 11
NUDGE_RIGHT = 12
UNDEFINED = 100



_PARTICLEFILTERDEBUGINFO = _descriptor.Descriptor(
  name='ParticleFilterDebugInfo',
  full_name='senseAD.pp.ParticleFilterDebugInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p_yeild', full_name='senseAD.pp.ParticleFilterDebugInfo.p_yeild', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x_avg', full_name='senseAD.pp.ParticleFilterDebugInfo.x_avg', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y_avg', full_name='senseAD.pp.ParticleFilterDebugInfo.y_avg', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v_yield_avg', full_name='senseAD.pp.ParticleFilterDebugInfo.v_yield_avg', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v_not_yield_avg', full_name='senseAD.pp.ParticleFilterDebugInfo.v_not_yield_avg', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='theta_avg', full_name='senseAD.pp.ParticleFilterDebugInfo.theta_avg', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intension_avg', full_name='senseAD.pp.ParticleFilterDebugInfo.intension_avg', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tgt_velocity_avg', full_name='senseAD.pp.ParticleFilterDebugInfo.tgt_velocity_avg', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x_obser', full_name='senseAD.pp.ParticleFilterDebugInfo.x_obser', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y_obser', full_name='senseAD.pp.ParticleFilterDebugInfo.y_obser', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v_obser', full_name='senseAD.pp.ParticleFilterDebugInfo.v_obser', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='theta_obser', full_name='senseAD.pp.ParticleFilterDebugInfo.theta_obser', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='senseAD.pp.ParticleFilterDebugInfo.timestamp', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=310,
)


_ESTIMATIONDEBUGINFO = _descriptor.Descriptor(
  name='EstimationDebugInfo',
  full_name='senseAD.pp.EstimationDebugInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filter_infos', full_name='senseAD.pp.EstimationDebugInfo.filter_infos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=392,
)


_RANGEPROTO = _descriptor.Descriptor(
  name='RangeProto',
  full_name='senseAD.pp.RangeProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='senseAD.pp.RangeProto.start', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='senseAD.pp.RangeProto.end', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=434,
)


_TIMETAGPROTO = _descriptor.Descriptor(
  name='TimeTagProto',
  full_name='senseAD.pp.TimeTagProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='longi_tag', full_name='senseAD.pp.TimeTagProto.longi_tag', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longi_time_range', full_name='senseAD.pp.TimeTagProto.longi_time_range', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lateral_tag', full_name='senseAD.pp.TimeTagProto.lateral_tag', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lateral_time_range', full_name='senseAD.pp.TimeTagProto.lateral_time_range', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=653,
)


_TIMETAGMAPPROTO = _descriptor.Descriptor(
  name='TimeTagMapProto',
  full_name='senseAD.pp.TimeTagMapProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_seq', full_name='senseAD.pp.TimeTagMapProto.id_seq', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag_seq', full_name='senseAD.pp.TimeTagMapProto.tag_seq', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=655,
  serialized_end=731,
)

_ESTIMATIONDEBUGINFO.fields_by_name['filter_infos'].message_type = _PARTICLEFILTERDEBUGINFO
_TIMETAGPROTO.fields_by_name['longi_tag'].enum_type = _OBSTACLETAGPROTO
_TIMETAGPROTO.fields_by_name['longi_time_range'].message_type = _RANGEPROTO
_TIMETAGPROTO.fields_by_name['lateral_tag'].enum_type = _OBSTACLETAGPROTO
_TIMETAGPROTO.fields_by_name['lateral_time_range'].message_type = _RANGEPROTO
_TIMETAGMAPPROTO.fields_by_name['tag_seq'].message_type = _TIMETAGPROTO
DESCRIPTOR.message_types_by_name['ParticleFilterDebugInfo'] = _PARTICLEFILTERDEBUGINFO
DESCRIPTOR.message_types_by_name['EstimationDebugInfo'] = _ESTIMATIONDEBUGINFO
DESCRIPTOR.message_types_by_name['RangeProto'] = _RANGEPROTO
DESCRIPTOR.message_types_by_name['TimeTagProto'] = _TIMETAGPROTO
DESCRIPTOR.message_types_by_name['TimeTagMapProto'] = _TIMETAGMAPPROTO
DESCRIPTOR.enum_types_by_name['ObstacleTagProto'] = _OBSTACLETAGPROTO

ParticleFilterDebugInfo = _reflection.GeneratedProtocolMessageType('ParticleFilterDebugInfo', (_message.Message,), dict(
  DESCRIPTOR = _PARTICLEFILTERDEBUGINFO,
  __module__ = 'debug_info_pb2'
  # @@protoc_insertion_point(class_scope:senseAD.pp.ParticleFilterDebugInfo)
  ))
_sym_db.RegisterMessage(ParticleFilterDebugInfo)

EstimationDebugInfo = _reflection.GeneratedProtocolMessageType('EstimationDebugInfo', (_message.Message,), dict(
  DESCRIPTOR = _ESTIMATIONDEBUGINFO,
  __module__ = 'debug_info_pb2'
  # @@protoc_insertion_point(class_scope:senseAD.pp.EstimationDebugInfo)
  ))
_sym_db.RegisterMessage(EstimationDebugInfo)

RangeProto = _reflection.GeneratedProtocolMessageType('RangeProto', (_message.Message,), dict(
  DESCRIPTOR = _RANGEPROTO,
  __module__ = 'debug_info_pb2'
  # @@protoc_insertion_point(class_scope:senseAD.pp.RangeProto)
  ))
_sym_db.RegisterMessage(RangeProto)

TimeTagProto = _reflection.GeneratedProtocolMessageType('TimeTagProto', (_message.Message,), dict(
  DESCRIPTOR = _TIMETAGPROTO,
  __module__ = 'debug_info_pb2'
  # @@protoc_insertion_point(class_scope:senseAD.pp.TimeTagProto)
  ))
_sym_db.RegisterMessage(TimeTagProto)

TimeTagMapProto = _reflection.GeneratedProtocolMessageType('TimeTagMapProto', (_message.Message,), dict(
  DESCRIPTOR = _TIMETAGMAPPROTO,
  __module__ = 'debug_info_pb2'
  # @@protoc_insertion_point(class_scope:senseAD.pp.TimeTagMapProto)
  ))
_sym_db.RegisterMessage(TimeTagMapProto)


# @@protoc_insertion_point(module_scope)
