# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(930, 920)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_disk_list = QtWidgets.QLabel(self.centralwidget)
        self.label_disk_list.setGeometry(QtCore.QRect(30, 30, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_disk_list.setFont(font)
        self.label_disk_list.setObjectName("label_disk_list")
        self.listView_disk_list = QtWidgets.QListView(self.centralwidget)
        self.listView_disk_list.setGeometry(QtCore.QRect(30, 60, 256, 211))
        self.listView_disk_list.setObjectName("listView_disk_list")
        self.label_mission_info = QtWidgets.QLabel(self.centralwidget)
        self.label_mission_info.setGeometry(QtCore.QRect(30, 300, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_mission_info.setFont(font)
        self.label_mission_info.setObjectName("label_mission_info")
        self.label_error_info = QtWidgets.QLabel(self.centralwidget)
        self.label_error_info.setGeometry(QtCore.QRect(30, 640, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_error_info.setFont(font)
        self.label_error_info.setObjectName("label_error_info")
        self.pushButton_up = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_up.setGeometry(QtCore.QRect(310, 110, 99, 27))
        self.pushButton_up.setObjectName("pushButton_up")
        self.pushButton_down = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_down.setGeometry(QtCore.QRect(310, 150, 99, 27))
        self.pushButton_down.setObjectName("pushButton_down")
        self.pushButton_pause_resume = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pause_resume.setGeometry(QtCore.QRect(310, 190, 99, 27))
        self.pushButton_pause_resume.setObjectName("pushButton_pause_resume")
        self.label_cmd = QtWidgets.QLabel(self.centralwidget)
        self.label_cmd.setGeometry(QtCore.QRect(450, 250, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_cmd.setFont(font)
        self.label_cmd.setObjectName("label_cmd")
        self.lineEdit_cmd = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_cmd.setGeometry(QtCore.QRect(540, 250, 361, 27))
        self.lineEdit_cmd.setObjectName("lineEdit_cmd")
        self.label_history = QtWidgets.QLabel(self.centralwidget)
        self.label_history.setGeometry(QtCore.QRect(450, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_history.setFont(font)
        self.label_history.setObjectName("label_history")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(540, 30, 181, 27))
        self.comboBox.setObjectName("comboBox")
        self.tableWidget_mission_info = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_mission_info.setGeometry(QtCore.QRect(30, 330, 870, 280))
        self.tableWidget_mission_info.setObjectName("tableWidget_mission_info")
        self.tableWidget_mission_info.setColumnCount(0)
        self.tableWidget_mission_info.setRowCount(0)
        self.tableWidget_error_info = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_error_info.setGeometry(QtCore.QRect(30, 670, 870, 160))
        self.tableWidget_error_info.setObjectName("tableWidget_error_info")
        self.tableWidget_error_info.setColumnCount(0)
        self.tableWidget_error_info.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 930, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数据产线V2.0"))
        self.label_disk_list.setText(_translate("MainWindow", "已加载硬盘："))
        self.label_mission_info.setText(_translate("MainWindow", "任务详情："))
        self.label_error_info.setText(_translate("MainWindow", "错误信息："))
        self.pushButton_up.setText(_translate("MainWindow", "上移"))
        self.pushButton_down.setText(_translate("MainWindow", "下移"))
        self.pushButton_pause_resume.setText(_translate("MainWindow", "暂停/恢复"))
        self.label_cmd.setText(_translate("MainWindow", "指令输入："))
        self.label_history.setText(_translate("MainWindow", "历史记录："))

